modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/PigCart/item-wheel/issues"
license = "MIT"

[[mods]]
modId = "itemwheel"
version = "${version}"
displayName = "Wheel"
authors = "PigCart"
description = '''
adds a wheel to dispensery blocks
'''
#logoFile = ""

[[dependencies.wheel]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wheel]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wheel]]
modId = "architectury"
mandatory = true
versionRange = "[8.2.89,)"
ordering = "AFTER"
side = "BOTH"